### ISSUE TITLE
conflict in right_tmm

### ISSUE THREAD

**Issue by billzt** [drmaize/ThermoAlign#3]
The right_tmm definition in https://github.com/drmaize/ThermoAlign/blob/master/TA_codes/Santalucia_NN_Tm.py#L205 is in conflict with https://github.com/biopython/biopython/blob/master/Bio/SeqUtils/MeltingTemp.py#L904

Santalucia_NN_Tm.py#L205: 
```python
right_tmm = temp_compl_seq[-2:] + '/' + temp_seq[-2:]
```

MeltingTemp.py#L904
```python
right_tmm = tmp_seq[-2:] + '/' + tmp_cseq[-2:]
```

**Comment by ffrancis** [comment]
Thank you for pointing this out. Santalucia_NN_Tm.py has been updated.
